### PR TITLE
Add support for Moondrop Moonriver 2 Ti

### PR DESCRIPTION
**Pull request by alexandru0-dev**
As the title says
Tho probably a refactor is needed as of now Mooonriver2 Ti uses the Dawn classes and everything else, as it shares every feature with the Dawn class even tho it is not a Dawn dac.

Edit: typo

### CODE REVIEW

**Comment by Tommy-Geenexus** [comment]
Thanks. Has this been confirmed working on the device? I don't own the moonriver, and can't verify myself.
It does need some refactoring, i'll review further later on, it will take some time.

**Comment by alexandru0-dev** [comment]
Yup, I built the apk in debug and tested as I own both a dawn 4.4 and a moonriver2 ti and it worked perfectly.

It's detected, and changes made in the moondrop (link) app are detected by your app and vice versa.

**Comment by alexandru0-dev** [comment]
It was basically a copy-paste work tbh as I based my work on the dawn3.5 commit

**Comment by alexandru0-dev** [comment]
@Tommy-Geenexus any update on this PR?

**Comment by Tommy-Geenexus** [comment]
I'll add support for the moonriver based on your pr, the project structure will change a bit. I think thats better than you having to deal with refactoring this pr

**Comment by alexandru0-dev** [comment]
ohh that sounds perfect
I just saw the `wip` branch, ping me when the moonriver is ported so I can test it if needed

**Comment by Tommy-Geenexus** [comment]
@alexandru0-dev I've implemented this on the a15 branch, can you build and test it/give feedback? Thanks!

**Pull request closed without merging**
